name: Build and Run JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Run JAR file
        run: java -jar target/ci-cd-test-1.0-SNAPSHOT.jar

      # - name: Upload JAR artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-app-jar
      #     path: target/*.jar
